name: pertama_aplikasi
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  pdf: ^3.10.4
  printing: ^5.12.0
  share_plus: ^7.2.1
  excel: ^2.0.6 # untuk ekspor Excel sederhana
  path_provider: ^2.1.2
  intl: ^0.19.0
  flutter_blue_plus: ^1.15.3
  esc_pos_utils_plus: 2.0.4
  blue_thermal_printer: ^1.1.5
  whatsapp_unilink: ^2.0.1
  open_file: ^3.5.10
  syncfusion_flutter_pdf: ^31.1.20
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/.env
